//// Hand-rolled property-based tests for sparklinekit.
////
//// `qcheck` is not currently a dependency of sparklinekit, so each
//// property iterates over a deterministic corpus generated by a
//// linear-congruential walk over a known seed range. Every property
//// is bounded — at most a few hundred cases per test — and every
//// case is reproducible from the seed.
////
//// The properties asserted here are the *should always hold* claims
//// the package makes (often implicitly):
////
//// - `unicode.render` length equals input length for non-empty input.
//// - Output uses only the eight-block vocabulary.
//// - SVG output is always a well-formed `<svg>...</svg>` wrapper.
//// - PNG output always starts with the 8-byte PNG signature.
//// - The renderer is total — it never panics on a finite input.

import gleam/bit_array
import gleam/int
import gleam/list
import gleam/string
import gleeunit/should
import sparklinekit/bar
import sparklinekit/line
import sparklinekit/theme
import sparklinekit/unicode

const block_alphabet: List(String) = ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"]

// --- Unicode --------------------------------------------------------

pub fn unicode_length_property_test() {
  list_range(1, 200)
  |> list.each(fn(seed) {
    let xs = gen_floats(seed, modulo(seed, 32) + 1)
    let out = unicode.render(xs)
    string.length(out) |> should.equal(list.length(xs))
  })
}

pub fn unicode_block_alphabet_property_test() {
  list_range(1, 100)
  |> list.each(fn(seed) {
    let xs = gen_floats(seed, modulo(seed, 20) + 1)
    let out = unicode.render(xs)
    string.to_graphemes(out)
    |> list.each(fn(g) { list.contains(block_alphabet, g) |> should.be_true })
  })
}

pub fn unicode_total_on_arbitrary_floats_test() {
  list_range(1, 100)
  |> list.each(fn(seed) {
    let xs = gen_floats(seed, modulo(seed, 40) + 1)
    // Must not panic regardless of value distribution.
    let _ = unicode.render(xs)
    Nil
  })
}

// --- SVG well-formedness -------------------------------------------

pub fn line_svg_always_wrapped_test() {
  list_range(1, 50)
  |> list.each(fn(seed) {
    let xs = gen_floats(seed, modulo(seed, 12) + 1)
    let svg = line.new(xs) |> line.to_svg
    string.starts_with(svg, "<svg") |> should.be_true
    string.ends_with(svg, "</svg>") |> should.be_true
  })
}

pub fn bar_svg_always_wrapped_test() {
  list_range(1, 50)
  |> list.each(fn(seed) {
    let xs = gen_floats_signed(seed, modulo(seed, 12) + 1)
    let svg = bar.new(xs) |> bar.to_svg
    string.starts_with(svg, "<svg") |> should.be_true
    string.ends_with(svg, "</svg>") |> should.be_true
  })
}

pub fn line_svg_carries_viewbox_test() {
  list_range(1, 30)
  |> list.each(fn(seed) {
    let xs = gen_floats(seed, modulo(seed, 8) + 1)
    let svg =
      line.new(xs)
      |> line.with_size(100 + modulo(seed, 400), 30 + modulo(seed, 80))
      |> line.to_svg
    string.contains(svg, "viewBox=") |> should.be_true
  })
}

pub fn bar_svg_carries_viewbox_test() {
  list_range(1, 30)
  |> list.each(fn(seed) {
    let xs = gen_floats(seed, modulo(seed, 8) + 1)
    let svg =
      bar.new(xs)
      |> bar.with_size(100 + modulo(seed, 400), 30 + modulo(seed, 80))
      |> bar.to_svg
    string.contains(svg, "viewBox=") |> should.be_true
  })
}

// --- PNG signature -------------------------------------------------

pub fn line_png_starts_with_signature_property_test() {
  let signature = <<137, 80, 78, 71, 13, 10, 26, 10>>
  list_range(1, 30)
  |> list.each(fn(seed) {
    let xs = gen_floats(seed, modulo(seed, 8) + 1)
    let png =
      line.new(xs)
      |> line.with_theme(theme.ocean())
      |> line.to_png
    case bit_array.slice(png, 0, 8) {
      Ok(head) -> head |> should.equal(signature)
      Error(_) -> should.fail()
    }
  })
}

pub fn bar_png_starts_with_signature_property_test() {
  let signature = <<137, 80, 78, 71, 13, 10, 26, 10>>
  list_range(1, 30)
  |> list.each(fn(seed) {
    let xs = gen_floats_signed(seed, modulo(seed, 8) + 1)
    let png =
      bar.new(xs)
      |> bar.with_theme(theme.amber())
      |> bar.to_png
    case bit_array.slice(png, 0, 8) {
      Ok(head) -> head |> should.equal(signature)
      Error(_) -> should.fail()
    }
  })
}

// --- Theme application -----------------------------------------------

pub fn line_themed_svg_contains_theme_foreground_test() {
  let themes = [
    #(theme.ocean(), "#2563EB"),
    #(theme.forest(), "#10B981"),
    #(theme.sunset(), "#F97316"),
    #(theme.mono(), "#0F172A"),
    #(theme.neon(), "#22D3EE"),
    #(theme.pastel(), "#A78BFA"),
    #(theme.crimson(), "#DC2626"),
    #(theme.slate(), "#475569"),
    #(theme.amber(), "#F59E0B"),
    #(theme.midnight(), "#F8FAFC"),
  ]
  list.each(themes, fn(pair) {
    let #(t, expected_fg) = pair
    let svg =
      line.new([1.0, 2.0, 3.0])
      |> line.with_theme(t)
      |> line.to_svg
    string.contains(svg, "stroke=\"" <> expected_fg <> "\"")
    |> should.be_true
  })
}

pub fn bar_themed_svg_contains_theme_foreground_test() {
  let themes = [
    #(theme.ocean(), "#2563EB"),
    #(theme.forest(), "#10B981"),
    #(theme.sunset(), "#F97316"),
    #(theme.mono(), "#0F172A"),
    #(theme.neon(), "#22D3EE"),
    #(theme.pastel(), "#A78BFA"),
    #(theme.crimson(), "#DC2626"),
    #(theme.slate(), "#475569"),
    #(theme.amber(), "#F59E0B"),
    #(theme.midnight(), "#F8FAFC"),
  ]
  list.each(themes, fn(pair) {
    let #(t, expected_fg) = pair
    let svg =
      bar.new([1.0, 2.0, 3.0])
      |> bar.with_theme(t)
      |> bar.to_svg
    string.contains(svg, "fill=\"" <> expected_fg <> "\"")
    |> should.be_true
  })
}

// --- helpers --------------------------------------------------------

fn list_range(lo: Int, hi: Int) -> List(Int) {
  case lo > hi {
    True -> []
    False -> do_list_range(hi, lo, [])
  }
}

fn do_list_range(current: Int, lo: Int, acc: List(Int)) -> List(Int) {
  case current < lo {
    True -> acc
    False -> do_list_range(current - 1, lo, [current, ..acc])
  }
}

fn modulo(value: Int, divisor: Int) -> Int {
  case int.modulo(value, divisor) {
    Ok(r) -> r
    Error(_) -> 0
  }
}

/// Deterministic floats in `[0.0, 1000.0)` via a simple linear-
/// congruential walk. Same seed → same list.
fn gen_floats(seed: Int, count: Int) -> List(Float) {
  do_gen(seed, count, [], False)
  |> list.reverse
}

fn gen_floats_signed(seed: Int, count: Int) -> List(Float) {
  do_gen(seed, count, [], True)
  |> list.reverse
}

fn do_gen(
  state: Int,
  remaining: Int,
  acc: List(Float),
  signed: Bool,
) -> List(Float) {
  case remaining <= 0 {
    True -> acc
    False -> {
      let next = step(state)
      let unsigned = modulo(next, 1000)
      let f_unsigned = int.to_float(unsigned)
      let value = case signed && modulo(next, 2) == 0 {
        True -> 0.0 -. f_unsigned
        False -> f_unsigned
      }
      do_gen(next, remaining - 1, [value, ..acc], signed)
    }
  }
}

fn step(state: Int) -> Int {
  // Numerical Recipes LCG constants, kept inside Int range.
  let mixed = state * 1_664_525 + 1_013_904_223
  case mixed < 0 {
    True -> 0 - mixed
    False -> mixed
  }
}
